capstone/blueprints/login.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from capstone.forms import LoginForm
from capstone.models import User


# define our blueprint
login_bp = Blueprint('login', __name__)

@login_bp.route("/" , methods = ['POST' , 'GET'])
@login_bp.route('/login', methods=['POST', 'GET'])
def login():
    """This function validates the user's login credentials then takes them to the Home page."""
    # created an instance of our form
    login_form = LoginForm()

    # check if it is a form submission
    if login_form.validate_on_submit():

        # read values from the login wtform
        username = login_form.username.data
        password = login_form.password.data

        user = User.objects(username=username).first()

        # check if credentials are valid
        if (user) and (user.authenticate(username, password)):
            session['user'] = user.serialize()

            # redirect the user after login
            return redirect(url_for('home.home'))

        else:
            # invalid credentials, redirect to login with error message
            flash("Login invalid. Please check your username and password.")
            return redirect(url_for('login.login'))

        return redirect(url_for('profile.profile'))

    # render the login template
    return render_template('login/login.html', form = login_form , icon = 'fas fa-sign-in-alt' , title = 'Log-In')


@login_bp.route('/session')
def show_session():
    """This function prints out the Session dictionary.
    This is only accessable through the URL and is used by the site developers for testing."""
    return dict(session)


@login_bp.route('/logout')
def logout():
    """This function removes the logged in user's information from the Session dictionary."""
    # clear all data from session
    session.clear()

    # redirect to index
    return redirect(url_for('login.login'))

capstone/blueprints/profile.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from capstone.models import User , BuyRequest ,Item , UpgradeRequest ,Category
from bson.objectid import ObjectId
from .user import disable_user , login_required , maintenance
from capstone.forms.items import AddCategoryForm

# define our blueprint
profile_bp = Blueprint('profile', __name__)

@profile_bp.route('/profile', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def profile():
    """This function displays the logged in user's information."""
    user = User.objects(id = session["user"]['id']).first()

    return render_template('profile/profile.html' , user = user)


@profile_bp.route('/display_users', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def display_users():
    """This function is for the Admin only (if statement in the template)
    It lets them preview all the users and their status.
    Also, it allows the admin to Delete or Disable any user(s)."""

    users = User.objects()
    items = Item.objects()
    seller_user = User.objects(role = 1)
    buyer_user = User.objects(role = 0)
    return render_template('profile/display_users.html', buyer_user = buyer_user , seller_user = seller_user , users = users , items = items , title = 'All-Users' , icon = 'fas fa-users')


@profile_bp.route('/remove_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def remove_user(user_id):
    """This function removes the user specified from the database."""
    
    user = User.objects(id = user_id).first()
    user.delete()

    flash(f"Account '{user.username}' has been deleted.!")

    return redirect(url_for('profile.display_users'))


@profile_bp.route('/disable_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def disable_user_list(user_id) :
    """This function sets the "disable" attribute of the user to "True".
    Such user can't access anything on the site (because of the decorator)."""

    user = User.objects(id = user_id).first()
    
    user.disable = True

    user.save()

    flash(f"Account '{user.username}' has been disabled.!")


    return redirect(url_for('profile.display_users'))


@profile_bp.route('/unlock_disable_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def unlock_disable_user_user_list(user_id) :
    """This function sets the "disable" attribute of the user to "False".
    Such user can now use the site as usual with no restrictions."""    
    user = User.objects(id = user_id).first()
    
    user.disable = False

    user.save()

    flash(f"Account '{user.username}' has been unlocked.!")


    return redirect(url_for('profile.display_users'))


@profile_bp.route('/profile/maintenance', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def maintenance_mode() :
    """This function sets the "maintenance" attribute of all users to "True".
    All users will see the Maintenance Page when trying to access any page on the site."""

    User.objects(role = 1).update(maintenance = True) 
    User.objects(role = 0 ).update(maintenance = True)
    flash('The Website now in Maintenance!')

    return redirect(url_for('profile.profile'))


@profile_bp.route('/profile/remove_maintenance_mode', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def remove_maintenance_mode() :
    """This function sets the "maintenance" attribute of all users to "False".
    All users will be able to access any page on the site normally."""

    User.objects(role = 0 ).update(maintenance = False) 
    User.objects(role = 1 ).update(maintenance = False) 
    
    flash('The Website now on!')
    
    return redirect(url_for('profile.profile'))


@profile_bp.route('/disable_users_list', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance  
def disabled_list():
    """This function can be accessed by the Admin user to view which users they have locked(disable)."""
    users = User.objects(disable = True)

    return render_template('profile/blocked_list.html' , users = users, title = "Blocked-List" , icon = 'fas fa-users')
    

@profile_bp.route('/buy_request_list/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance 
def buy_request_list(user_id):
    """This function is accessed by the Buyer user to view their Buy Requests and their status."""

    list_request = BuyRequest.objects(user = session['user']['id'])

    return render_template('profile/buy_request_list.html'  , list_request = list_request ,title = 'Buy-Request' , icon = 'fas fa-shopping-cart')



@profile_bp.route('/user/favorite_list', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance 
def view_favorite():
    """This function lets the Buyer user see their favorited items."""
    favorite_items = User.objects(id = session['user']['id']).get().favorite

    items = []
   
    for item in range(0 ,len(favorite_items)):

        item = Item.objects(id = favorite_items[item]).first()

        items.append(item)
        
    
    return render_template("profile/user_favorite_items.html" , items = items , title = 'Favorites-Items' , icon = 'fas fa-star')


# @profile_bp.route('/request_upgrade', methods=['GET', 'POST'])
# @login_required
# @disable_user
# @maintenance 
# def request_upgrade():

#     request = UpgradeRequest.objects(user = session['user']['id']).first()

#     if not request:

#         upgrade_request = UpgradeRequest(user = session['user']['id'], status = "Pending")

#         upgrade_request.save()

#     else:

#         flash("You have already requested an upgrade.")

#     return redirect(url_for('profile.profile'))


@profile_bp.route('/add_category', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def add_category():
    """This function is accessed by the Admin only, it lets them add a new category for items.
    The changes made here can be viewed when a Seller user chooses a category when adding a new item."""

    add_category_form = AddCategoryForm()

    if add_category_form.validate_on_submit():


        category_value = add_category_form.value.data
        category_label = add_category_form.label.data

        new_category = Category( value = category_value, label = category_label)

        new_category.save()
        
        flash('New Category has been added.!')

        return redirect(url_for("profile.profile"))

    return render_template("profile/add_category.html", form = add_category_form)

capstone/blueprints/signup.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, PasswordField
from capstone.forms import SignUpForm
from capstone.models import User

# define our blueprint
signup_bp = Blueprint('signup', __name__)

@signup_bp.route("/signup" , methods = ['POST' , 'GET'])
def signup():
    """This function creates an account for a new user."""
    # created an instance of our form
    signup_form = SignUpForm()

    # check if it is a form submission
    if signup_form.validate_on_submit():

        #create instance from user model
        user = User()
        
        # read values from the login wtform
        user.username = signup_form.username.data
        user.first_name = signup_form.first_name.data
        user.last_name = signup_form.last_name.data
        user.password = user.encrypt_password(signup_form.password.data)
        user.email = signup_form.email.data
        user.birthday = signup_form.birthday.data

        # save the user object
        user.save()

        return redirect(url_for("login.login"))

    return render_template("sign-up/sign-up.html" , form = signup_form , title = 'Sign-Up' , icon = 'fas fa-user-plus')    

capstone/blueprints/user.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for 
from flask_wtf import FlaskForm
from capstone.models import User , Item
from capstone.forms.edit_profile import EditProfileForm  , ChangePasswordForm
from capstone.forms.items import AddItemForm , EditItemForm
from bson import ObjectId
from functools import wraps

# define our blueprint
user_bp = Blueprint('user', __name__)


def login_required(function):
    """Login Decorator: 
    This function checks whether the user is logged in before accessing a functionality.
    If not; the user is taken to the Login Page."""
    @wraps(function)
    def check_required(*args, **kwargs):

        try:  
            session['user']['id'] 
            return function(*args, **kwargs)

        except:
            
            return redirect(url_for('login.login'))

    return check_required


def disable_user(function):
    """Disable Decorator: 
    This function checks whether the user "disable" attribute is set to "False" before accessing a functionality.
    If not; then the admin account has set this user's "disable" to "True" and is taken to the Disable Page."""
    @wraps(function)
    def check(*args, **kwargs):

        try:
            if session['user']['disable'] == False :
                return function(*args, **kwargs)

            else :
                return render_template('user/disable.html')
        except:
            return render_template('user/disable.html')
    
    return check


def maintenance(function):
    """Maintenance Decorator: 
    This function checks whether the user "maintenance" attribute is set to "False" before accessing a functionality.
    If not; then the admin account has set all users' "maintenance" to "True" and are taken to the Maintenance Page."""
    @wraps(function)
    def check(*args, **kwargs):

        try:
            if session['user']['maintenance'] == False:
                return function(*args, **kwargs)

            else :
                return render_template('user/maintenance.html')

        except:
            return render_template('user/maintenance.html')
    
    return check

    
@user_bp.route('/user/edit_profile', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def edit_profile_user():
    """This function provides the user with a form to edit their information."""
    user = User.objects(id = session["user"]['id']).first()

    edit_profile_form = EditProfileForm()
    
    if request.method == "GET":

    #set values in the form
        
        edit_profile_form.new_first_name.data = session['user']['first_name']
        edit_profile_form.new_last_name.data = session['user']['last_name']

    if  edit_profile_form.validate_on_submit():

        new_first_name = edit_profile_form.new_first_name.data
        new_last_name = edit_profile_form.new_last_name.data
    
        user.first_name = new_first_name
        user.last_name = new_last_name
        

        user.save()

        session['user'] = user.serialize()

        return redirect(url_for('profile.profile')) 

    return render_template("user/edit_profile_user.html", form = edit_profile_form , title = 'Edit-Profile' , icon = 'fas fa-user-edit')


@user_bp.route('/user/change_password', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def change_password():
    """This function allows the user to change/update their password
    It is a seperate functionality from "Edit Profile" for extra validation and seperation of concerns."""


    user = User.objects(id=session['user']['id']).first()

    change_password_form = ChangePasswordForm()

    if change_password_form.validate_on_submit():

        # read post values from the form
        current_password = change_password_form.current_password.data
        new_password = change_password_form.new_password.data

        if (user):
            user.change_password(current_password, new_password)
            user.save()
            flash("Your password has been successfully changed.")
            return redirect(url_for('profile.profile'))

    return render_template("user/change_password.html", form=change_password_form , title = 'Change-Password' , icon = 'fas fa-key') 

capstone/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" />

  <title>{%block title%}Home{%endblock%}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="../static/css/nav-css.css">
</head>

<body>
  <!-- header -->
  <header>
    {#
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">New</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Trending</a>
          </li>
          {% if session['user'] %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Posts
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Favorites</a>
              <a class="dropdown-item" href="#">Drafts</a>
              <a class="dropdown-item" href="#">Published</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Search</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{session['user'].username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Profile</a>
              <a class="dropdown-item" href="#">Change Password</a>
              <a>
                <hr class="dropdown-divider">
              </a>
              <a class="dropdown-item" href="#">Log out</a>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav> -->
    #}

    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <a class="navbar-brand" href="#">HRD-Souq</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-6 topnav">

          {% if session ['user'] %}


          <li class="nav-item">
            <a class="nav-link" href="{{url_for('home.home')}}">Home
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('profile.profile')}}">Profile</a>
          </li>


          {% if session['user']['role'] == 2 %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('notifications.review_upgrade_requests')}}">Notifications</a>
          </li>
          {% elif session['user']['role'] == 1 %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('notifications.view_buy_request')}}">Notifications</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link"
              href="{{url_for('profile.buy_request_list' , user_id = session['user']['id'])}}">Notifications</a>
          </li>
          {% endif %}



          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Account-Settings
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('user.edit_profile_user')}}"><i class="fas fa-user-edit"></i>
                Edit-Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('user.change_password')}}"><i class="fas fa-key"></i>
                Change-Password</a>
            </div>
          </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto topnav">
          {% if not session ['user'] %}

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('signup.signup')}}">Sign-Up <i class="fas fa-user-plus"
                title="Sign-Up"></i>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('login.login')}}">Log-In <i class="fas fa-sign-in-alt"
                title="Log-In"></i></i>
            </a>
          </li>
          {% endif %}


          {% if session ['user'] %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('login.logout')}}">Log-Out <i class="fas fa-sign-out-alt"
                title="Log-Out"></i>
            </a>
          </li>
          {% endif %}

        </ul>
      </div>

    </nav>

  </header>

  <!-- main -->
  <main class="mt-5">

    <!-- notification section -->
    <section class="container my-5">
      {% for message in get_flashed_messages() %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    </section>

    <!-- main block -->
    <section id="main" class="container">
      {%block main%}
      {%endblock%}
    </section>
  </main>
  <br><br>
  <br><br>

  {% block footer%}
  
  <footer class="text-muted py-4 bg-light" style="padding: 20px; position: relative; left: 0; bottom: 0; width: 100%; ">
    <div class="container">

      <center>
        <p class="mb-1 text-muted" style="color: black;">HRD-Souq is a simple website souq written in Flask and uses WTForms, Bootstrap, and
          MongoEngine.</p>
        <p class="mb-1 text-muted">By : Hamza Mohammad Rdaideh :)</p>
      </center>
    </div>
  </footer>
  {% endblock %}

  <!-- importing our scripts -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
    integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
    crossorigin="anonymous"></script>
</body>

</html>