capstone/blueprints/home.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from capstone.models import User , Item , Category
from capstone.forms.items import AddItemForm , EditItemForm
from capstone.models.request import BuyRequest
from bson import ObjectId
from .user import disable_user , login_required , maintenance

# define our blueprint
home_bp = Blueprint('home', __name__)






@home_bp.route('/home', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def home():
    """ This function is display unsold item """
    user = User.objects()
    items = Item.objects(sold = False)

    return render_template('item/home.html' ,user = user ,items = items)



@home_bp.route('/user/add_item', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def add_item():
    """This function is available for the Seller User, it provides them with a form to add an item for sale."""
    add_item_form = AddItemForm()

    categories = Category.objects()

    add_item_form.category.choices = [(category.value, category.label) for category in categories]

    if add_item_form.validate_on_submit():

        title = add_item_form.title.data
        description = add_item_form.description.data
        price = add_item_form.price.data
        category = add_item_form.category.data

        new_item = Item(user = session['user']['id'] , title = title, description = description, price = price, category = category)
        
        new_item.save()

        flash("Your item has been successfully added.")

        return redirect(url_for('home.home'))

    return render_template("item/add_item.html", form = add_item_form , title = 'Add-Item' , icon="fa fa-upload")


@home_bp.route('/user/<user_id>/edit_item/<item_id>', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def edit_item(user_id,item_id):
    """This function is available for the Seller User, it provides them with a form to edit an item of theirs.
    Another Seller user can try to edit an item that is not theirs but will be flashed by a message preventing them to do so."""
    
    edit_item_form = EditItemForm()

    categories = Category.objects()

    edit_item_form.category.choices = [(category.value, category.label) for category in categories]

    item = Item.objects(id = item_id).first()

    if request.method == "GET":

        edit_item_form.new_title.data = item.title
        edit_item_form.new_description.data = item.description
        edit_item_form.new_price.data = item.price
        edit_item_form.category.data = item.category

    if edit_item_form.validate_on_submit():

        item = Item.objects(id = item_id).first() 
        item_user = item.user
        user = User.objects(id = user_id).first()

        if user == item_user :
            item.title = edit_item_form.new_title.data
            item.description = edit_item_form.new_description.data
            item.price = edit_item_form.new_price.data
            item.category = edit_item_form.category.data
            
            item.save()

            flash("Your item has been successfully edit.")

            return redirect(url_for('home.home'))

        else: 
            flash('Not allowed')

        return redirect(url_for("home.home"))  


    return render_template("item/edit_item.html", form = edit_item_form , title = 'Edit-Item' , icon = 'far fa-edit')    

    
@home_bp.route('/user/<user_id>/delete_item/<item_id>', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def delete_item(user_id ,item_id):
    """This function is available for the Seller User, it allows them to delete an item of theirs.
    Another Seller user can try to delete an item that is not theirs but will be flashed by a message preventing them to do so."""


    item = Item.objects(id = item_id).first() 
    item_user = item.user
    user = User.objects(id = user_id).first()

    if user == item_user :
        Item.objects(id = item_id , user = user_id).first().delete()
        flash('Item has been deleted')
    else: 
        flash('Not allowed')

    return redirect(url_for("home.home"))  


@home_bp.route('/sort-item/date', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def sort_date_items():
    """This function brings items from the database ordered descendingly by the date of their addition for the user to view."""
    items = Item.objects.order_by('-date')

    return render_template("item/home.html" , items = items)        


@home_bp.route('/sort-item/price', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def sort_price_items():
    """This function brings items from the database ordered descendingly by their price for the user to view."""
   
    items = Item.objects.order_by('-price')

    return render_template("item/home.html" , items = items)    


@home_bp.route("/item/search", methods=['POST'])
@login_required
@disable_user
@maintenance
def search_items():
    """This function is used when a user searches for a word; it can either be in the title or description.
    If the word was in the title of an item and the description of another, the priority is for the title."""

    if request.method == 'POST':
        
        search_keyword = str(request.form['search_keyword'])  
        results = Item.objects.search_text(search_keyword).order_by('$text_score')
        
        return render_template("item/search-result.html" , items = results , search_keyword = search_keyword)  


@home_bp.route('/item/<item_id>/favorite')
@login_required
@disable_user
@maintenance
def add_favorite(item_id):
    """This function lets a Buyer user add items to the Favorites List."""

    User.objects(id = session['user']['id']).update_one(add_to_set__favorite = item_id)
    flash("Added as favorite !:)")
    return redirect(url_for('home.home'))          



@home_bp.route('/item/<item_id>/remove_favorite')
@login_required
@disable_user
@maintenance
def remove_from_favorite(item_id):
    """This function lets a Buyer user remove items from the Favorites List."""

    User.objects(id = session['user']['id']).update_one(pull__favorite = item_id)
    flash("Removed from favorite !:)")
    return redirect(url_for('profile.profile'))          


@home_bp.route('/item/<item_id>/buy')
@login_required
@disable_user
@maintenance
def buy_item(item_id):
    """This function allows a Buyer user to send a Buy Request to the seller of an item to be reviewed."""

    request = BuyRequest.objects(user = session['user']['id'], item = item_id).first()

    if not request:

        buy_request = BuyRequest(user = session['user']['id'], item = item_id, status = 'Pending')

        buy_request.save()
        
        Item.objects(id = item_id).update_one(add_to_set__buy_request_list = buy_request.id)

        flash("A Buy Requests has been Sent. !:)")


    else:
        flash("Item already in you Buy-Requests.")

    return redirect(url_for('home.home' , request = request))

capstone/blueprints/profile.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from capstone.models import User , BuyRequest ,Item , UpgradeRequest ,Category
from bson.objectid import ObjectId
from .user import disable_user , login_required , maintenance
from capstone.forms.items import AddCategoryForm

# define our blueprint
profile_bp = Blueprint('profile', __name__)

@profile_bp.route('/profile', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def profile():
    """This function displays the logged in user's information."""
    user = User.objects(id = session["user"]['id']).first()

    return render_template('profile/profile.html' , user = user)


@profile_bp.route('/display_users', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def display_users():
    """This function is for the Admin only (if statement in the template)
    It lets them preview all the users and their status.
    Also, it allows the admin to Delete or Disable any user(s)."""

    users = User.objects()
    items = Item.objects()
    seller_user = User.objects(role = 1)
    buyer_user = User.objects(role = 0)
    return render_template('profile/display_users.html', buyer_user = buyer_user , seller_user = seller_user , users = users , items = items , title = 'All-Users' , icon = 'fas fa-users')


@profile_bp.route('/remove_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def remove_user(user_id):
    """This function removes the user specified from the database."""
    
    user = User.objects(id = user_id).first()
    user.delete()

    flash(f"Account '{user.username}' has been deleted.!")

    return redirect(url_for('profile.display_users'))


@profile_bp.route('/disable_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def disable_user_list(user_id) :
    """This function sets the "disable" attribute of the user to "True".
    Such user can't access anything on the site (because of the decorator)."""

    user = User.objects(id = user_id).first()
    
    user.disable = True

    user.save()

    flash(f"Account '{user.username}' has been disabled.!")


    return redirect(url_for('profile.display_users'))


@profile_bp.route('/unlock_disable_user/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def unlock_disable_user_user_list(user_id) :
    """This function sets the "disable" attribute of the user to "False".
    Such user can now use the site as usual with no restrictions."""    
    user = User.objects(id = user_id).first()
    
    user.disable = False

    user.save()

    flash(f"Account '{user.username}' has been unlocked.!")


    return redirect(url_for('profile.display_users'))


@profile_bp.route('/profile/maintenance', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def maintenance_mode() :
    """This function sets the "maintenance" attribute of all users to "True".
    All users will see the Maintenance Page when trying to access any page on the site."""

    User.objects(role = 1).update(maintenance = True) 
    User.objects(role = 0 ).update(maintenance = True)
    flash('The Website now in Maintenance!')

    return redirect(url_for('profile.profile'))


@profile_bp.route('/profile/remove_maintenance_mode', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance    
def remove_maintenance_mode() :
    """This function sets the "maintenance" attribute of all users to "False".
    All users will be able to access any page on the site normally."""

    User.objects(role = 0 ).update(maintenance = False) 
    User.objects(role = 1 ).update(maintenance = False) 
    
    flash('The Website now on!')
    
    return redirect(url_for('profile.profile'))


@profile_bp.route('/disable_users_list', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance  
def disabled_list():
    """This function can be accessed by the Admin user to view which users they have locked(disable)."""
    users = User.objects(disable = True)

    return render_template('profile/blocked_list.html' , users = users, title = "Blocked-List" , icon = 'fas fa-users')
    

@profile_bp.route('/buy_request_list/<user_id>', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance 
def buy_request_list(user_id):
    """This function is accessed by the Buyer user to view their Buy Requests and their status."""

    list_request = BuyRequest.objects(user = session['user']['id'])

    return render_template('profile/buy_request_list.html'  , list_request = list_request ,title = 'Buy-Request' , icon = 'fas fa-shopping-cart')



@profile_bp.route('/user/favorite_list', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance 
def view_favorite():
    """This function lets the Buyer user see their favorited items."""
    favorite_items = User.objects(id = session['user']['id']).get().favorite

    items = []
   
    for item in range(0 ,len(favorite_items)):

        item = Item.objects(id = favorite_items[item]).first()

        items.append(item)
        
    
    return render_template("profile/user_favorite_items.html" , items = items , title = 'Favorites-Items' , icon = 'fas fa-star')


# @profile_bp.route('/request_upgrade', methods=['GET', 'POST'])
# @login_required
# @disable_user
# @maintenance 
# def request_upgrade():

#     request = UpgradeRequest.objects(user = session['user']['id']).first()

#     if not request:

#         upgrade_request = UpgradeRequest(user = session['user']['id'], status = "Pending")

#         upgrade_request.save()

#     else:

#         flash("You have already requested an upgrade.")

#     return redirect(url_for('profile.profile'))


@profile_bp.route('/add_category', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def add_category():
    """This function is accessed by the Admin only, it lets them add a new category for items.
    The changes made here can be viewed when a Seller user chooses a category when adding a new item."""

    add_category_form = AddCategoryForm()

    if add_category_form.validate_on_submit():


        category_value = add_category_form.value.data
        category_label = add_category_form.label.data

        new_category = Category( value = category_value, label = category_label)

        new_category.save()
        
        flash('New Category has been added.!')

        return redirect(url_for("profile.profile"))

    return render_template("profile/add_category.html", form = add_category_form)

capstone/blueprints/user.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for 
from flask_wtf import FlaskForm
from capstone.models import User , Item
from capstone.forms.edit_profile import EditProfileForm  , ChangePasswordForm
from capstone.forms.items import AddItemForm , EditItemForm
from bson import ObjectId
from functools import wraps

# define our blueprint
user_bp = Blueprint('user', __name__)


def login_required(function):
    """Login Decorator: 
    This function checks whether the user is logged in before accessing a functionality.
    If not; the user is taken to the Login Page."""
    @wraps(function)
    def check_required(*args, **kwargs):

        try:  
            session['user']['id'] 
            return function(*args, **kwargs)

        except:
            
            return redirect(url_for('login.login'))

    return check_required


def disable_user(function):
    """Disable Decorator: 
    This function checks whether the user "disable" attribute is set to "False" before accessing a functionality.
    If not; then the admin account has set this user's "disable" to "True" and is taken to the Disable Page."""
    @wraps(function)
    def check(*args, **kwargs):

        try:
            if session['user']['disable'] == False :
                return function(*args, **kwargs)

            else :
                return render_template('user/disable.html')
        except:
            return render_template('user/disable.html')
    
    return check


def maintenance(function):
    """Maintenance Decorator: 
    This function checks whether the user "maintenance" attribute is set to "False" before accessing a functionality.
    If not; then the admin account has set all users' "maintenance" to "True" and are taken to the Maintenance Page."""
    @wraps(function)
    def check(*args, **kwargs):

        try:
            if session['user']['maintenance'] == False:
                return function(*args, **kwargs)

            else :
                return render_template('user/maintenance.html')

        except:
            return render_template('user/maintenance.html')
    
    return check

    
@user_bp.route('/user/edit_profile', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def edit_profile_user():
    """This function provides the user with a form to edit their information."""
    user = User.objects(id = session["user"]['id']).first()

    edit_profile_form = EditProfileForm()
    
    if request.method == "GET":

    #set values in the form
        
        edit_profile_form.new_first_name.data = session['user']['first_name']
        edit_profile_form.new_last_name.data = session['user']['last_name']

    if  edit_profile_form.validate_on_submit():

        new_first_name = edit_profile_form.new_first_name.data
        new_last_name = edit_profile_form.new_last_name.data
    
        user.first_name = new_first_name
        user.last_name = new_last_name
        

        user.save()

        session['user'] = user.serialize()

        return redirect(url_for('profile.profile')) 

    return render_template("user/edit_profile_user.html", form = edit_profile_form , title = 'Edit-Profile' , icon = 'fas fa-user-edit')


@user_bp.route('/user/change_password', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def change_password():
    """This function allows the user to change/update their password
    It is a seperate functionality from "Edit Profile" for extra validation and seperation of concerns."""


    user = User.objects(id=session['user']['id']).first()

    change_password_form = ChangePasswordForm()

    if change_password_form.validate_on_submit():

        # read post values from the form
        current_password = change_password_form.current_password.data
        new_password = change_password_form.new_password.data

        if (user):
            user.change_password(current_password, new_password)
            user.save()
            flash("Your password has been successfully changed.")
            return redirect(url_for('profile.profile'))

    return render_template("user/change_password.html", form=change_password_form , title = 'Change-Password' , icon = 'fas fa-key') 

capstone/templates/profile/add_category.html
{% extends 'base.html' %}

{% block title %}Add-Category{% endblock %}


{% block main %}

<center>
  {% if session['user']['role'] == 2 %}
  <div>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <h2><i class="{{icon}}"></i> {{title}}</h2>
    </div>
  </div>
  <hr>


  <div id="b1">
    <div class="col-lg-4 col-md-6 col-sm-12">
      <form method="POST" action="">
        {{form.hidden_tag()}}
        <div class="row my-3">
          {{form.value.label(class_="form-label", for_="username")}}
          {{form.value(id_="username", class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.label.label(class_="form-label", for_="password")}}
          {{form.label(id_="username", class_="form-control")}}
        </div>

        <hr class="mb-4" />
        {{form.submit(class_="form-control bg-dark text-light")}}

      </form>

    </div>
  </div>

  {% else %}
  <br>
  <div class="alert alert-warning" role="alert">
    You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
  {% endif %}
</center>

{% endblock %}

capstone/templates/profile/blocked_list.html
{% extends 'base.html' %}
<!-- title -->
{% block title %}Disabled-List{% endblock %}

<!-- content block -->
{% block main %}

<!-- edit user -->
<center>{% if session['user']['role'] == 2 %}



    <div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <h2><i class="{{icon}}"></i> {{title}}</h2>
        </div>
    </div>

    <br>
    <div id="b1">
        <div class="col-lg-10 col-md-6 col-lg">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">{{users | count}} - Users</th>
                        <th scope="col">Username</th>
                        <th scope="col">First name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Action</th>


                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>


                        <th scope="row">{{loop.index}}</th>
                        <td>{{user.username}}</td>
                        <td>{{user.first_name}}</td>
                        <td>{{user.last_name}}</td>
                        <td>{{user.email}}</td>
                        <td>
                            <a href="{{url_for('profile.unlock_disable_user_user_list' , user_id = user.id)}}"> <i
                                    class="fas fa-unlock ml-3" title="Unlock"></i></a>
                        </td>

                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            <br><br>
            {% if users %}

            <a href="{{url_for('profile.display_users')}}"><button type="button"
                    class="btn btn-primary">Users-List</button></a>

        </div>
    </div>
    {% else %}
    <P>No Blocked Users, back to<a href="{{url_for('profile.display_users')}}"> Users-List</a> </P>

    {% endif %}


    {% else %}
    <br>
    <div class="alert alert-warning" role="alert">
        You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
    </div>
    {% endif %}
</center>

<br><br>
{% endblock %}

capstone/templates/profile/buy_request_list.html
{% extends 'base.html' %}
<!-- title -->
{% block title %}Buy-Request{% endblock %}

<!-- content block -->
{% block main %}

<!-- edit user -->

<center>
  {% if session['user']['role'] == 0 %}
  <div>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <h2><i class="{{icon}}"></i> {{title}}</h2>
    </div>
  </div>
  <hr>


  <br>

  <div class="container">
    <div class="row align-items-start">


      {% for request in list_request %}
      <div class="col">

        <div class="card" style="width: 18rem;">

          <img class="card-img-top" src="../../static/images/notification.jpg" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">
              <h5
                style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
                <b> HRD-Souq</b>
              </h5>
            </h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <p class="card-text">
            <h5><b>Title : </b>{{request.item.title}}</h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <h5><b>Description : </b>{{request.item.description}}</h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <h5><b>Price : </b> {{request.item.price}} JDs </h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <h5><b>Cateogory : </b> {{request.item.category}} </h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <h5><b>Cateogory : </b> {{request.item.date}} </h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <h5><b>Status : </b> {{request.status}} </h5>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            </p>


          </div>
        </div>
        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      </div>
      <br>
      {% endfor %}
    </div>
  </div>

  {% if not list_request %}
  <P>No Buy Requests, Do You Want To Buy Any Item?<a href="{{url_for('home.home')}}"> Buy-Item</a> </P>
  {% endif %}
  </div>
  </div>


    
  {% else %}
  <br>
  <div class="alert alert-warning" role="alert">
      You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
  {% endif %}
</center>
<br><br>
{% endblock %}

capstone/templates/profile/display_users.html
{% extends 'base.html' %}
<!-- title -->
{% block title %}Profile{% endblock %}

<!-- content block -->
{% block main %}

<!-- edit user -->
<center>
{% if session['user']['role'] == 2 %} 


    <div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <h2><i class="{{icon}}"></i>{{title}}</h2>
        </div>
        <div class="alert alert-warning" role="alert">
            Users : {{users | count}} - Buyer : {{buyer_user | count}} - Seller : {{seller_user | count}} - Items : {{items | count}}
          </div>
    </div>



    <br>
    <div id="b1">
        <div class="col-lg-10 col-md-6 col-lg">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">First name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Delete-Block</th>


            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>


                <th scope="row">{{loop.index}}</th>
                <td>{{user.username}}</td>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.email}}</td>
                <td>
                    <a href="{{url_for('profile.remove_user' , user_id = user.id)}}"><i class="fas fa-user-times ml-4" title="Remove-User"></i></a>
                    <a href="{{url_for('profile.disable_user_list' , user_id = user.id)}}"> <i class="fas fa-user-slash" title="Disable-User"></i></a>
                </td>

            </tr>
            {% endfor %}

        </tbody>
    </table>
    <a href="{{url_for('profile.disabled_list')}}"><button type="button" class="btn btn-primary">Block-Users-List</button></a>
    
    <br><br>

   </div></div>



{% else %}
<br>
<div class="alert alert-warning" role="alert">
    You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
{% endif %}
</center>
{% endblock %}

capstone/templates/profile/profile.html
{% extends 'base.html' %}
<!-- title -->
{% block title %}Profile{% endblock %}

<!-- content block -->
{% block main %}

<!-- edit user -->

<center>

    <div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <h2><i class="{{icon}}"></i>{{title}}</h2>
        </div>
    </div>
</center>
<center>


    {#
    <!-- Admin  -->
    #}

    {% if session['user']['role'] == 2 %}


    <a href="{{url_for('profile.display_users')}}"><button type="button"
            class="btn btn-primary">Display-Users</button></a>
    <a href="{{url_for('profile.add_category')}}"><button type="button"
            class="btn btn-primary">Add-Category</button></a>
    <a href="{{url_for('profile.maintenance_mode')}}"><button type="button"
            class="btn btn-primary">Maintanance-On</button></a>
    <a href="{{url_for('profile.remove_maintenance_mode')}}"><button type="button"
            class="btn btn-primary">Maintanance-Off</button></a>
    {% endif %}





    {#
    <!-- Seller  -->
    #}
    {% if session['user']['role'] == 1 %}

    <a href="{{url_for('user.edit_profile_user')}}"> <button type="button"
            class="btn btn-primary">Edit-Profile</button></a>
    <a href="{{url_for('user.change_password')}}"><button type="button"
            class="btn btn-primary">Change-Password</button></a>


    {% endif %}





    {#
    <!-- buyer  -->
    #}
    {% if session['user']['role'] == 0 %}

    <a href="{{url_for('profile.view_favorite')}}"><button type="button"
            class="btn btn-primary">Favorites-List</button></a>
    <a href="{{url_for('profile.buy_request_list' , user_id = user.id)}}"><button type="button"
            class="btn btn-primary">Your-Buy-Requests</button></a>
    <a href="{{url_for('notifications.upgrade_request')}}"><button type="button"
            class="btn btn-primary">Upgrade-Request</button></a>


    {% endif %}


    <br> <br>

    <div class="card" style="width: 18rem;">
        <img src="../../static/images/136.png" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">HRD-Souq</h5>
            <p class="card-text">Your Profile Details.</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Username : {{user.username}}</li>
            <li class="list-group-item">First Name : {{user.first_name | title}}</li>
            <li class="list-group-item">Last Name : {{user.last_name | title}}</li>
            <li class="list-group-item">Birthday : {{user.birthday}}</li>
            <li class="list-group-item">Email : {{user.email}}</li>
        </ul>

    </div>
    <br><br>
</center>
{% endblock %}

capstone/templates/profile/user_favorite_items.html
{% extends 'base.html' %}
<!-- title -->
{% block title %}Favorites-Item{% endblock %}

<!-- content block -->
{% block main %}

<!-- edit user -->

<center>
    {% if session['user']['role'] == 0 %}

    <div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <h2><i class="{{icon}}"></i> {{title}}</h2>
        </div>
    </div>
    <hr>


    <br>

    

    {% for item in items %}

                <div class="card" style="width: 18rem;">
                    <a href="{{url_for('home.remove_from_favorite' , item_id = item.id)}}"><i class="fas fa-heart-broken" title="Unfavorite"></i></a>

                    <img class="card-img-top" src="../../static/images/logi.png" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">
                            <h5><b>HRD-Souq.com</b></h5>
                        </h5>
                        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                        <p class="card-text">
                        <h5><b>Title : </b>{{item.title}}</h5>
                        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                        <h5><b>Description : </b>{{item.description}}</h5>
                        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                        <h5><b>Price : </b> {{item.price}} JDs </h5>
                        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                        </p>
                        
                    </div>
                </div>

    {% endfor %}
<br>
    {% if not items %}
    <P>No Item in Favorite List!<a href="{{url_for('home.home')}}"> Home-Page</a> </P>
    {% endif %}
    </div>
    </div>

    
  {% else %}
  <br>
  <div class="alert alert-warning" role="alert">
      You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
  {% endif %}
</center>
{% endblock %}