capstone/models/item.py
from mongoengine import *
from datetime import datetime
from flask import session
from .user import User
# from . request import BuyRequest 


class Item(Document):

    # define class metadata
    meta = {'collection' : 'Items',
             'indexes': [
                {'fields': ['$title', '$description'],
                 'default_language': 'english',
                 'weights': {'title': 10, 'description': 2}
                 }
            ]
            }


    # define class fields
    user = ReferenceField(User)
    title = StringField(required = True)
    description = StringField(required = True)
    date = DateTimeField(default = datetime.now())
    price = FloatField(required = True)
    sold = BooleanField(default = False)
    category = StringField(required = True)
    buy_request_list = ListField(StringField())
    hidden = BooleanField(default = False)

class Category(Document):

    meta = {'collection' : 'Categories'}

    value = StringField(required = True)
    label = StringField(required = True)

capstone/forms/add_item.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, TextAreaField, FloatField, SelectField, FileField


class AddItemForm(FlaskForm):

    title = StringField("Title: ", [validators.InputRequired()] , render_kw={"placeholder": "Like Car For Sale"})

    description = TextAreaField("Description: ", [validators.InputRequired()] , render_kw={"placeholder": "Like Toyota Camry model 2020 , Color-Black "})

    price = FloatField("Price: ", [validators.InputRequired()] , render_kw={"placeholder": "00.00 JDS"})

    category = SelectField("Category: ", choices=[('1', 'Clothes'), ('2', 'Vehicles'), ('3', 'Digital Devices')])

    image = FileField()

    submit = SubmitField("Add Item")

capstone/forms/items.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, TextAreaField, FloatField, SelectField, FileField


class AddItemForm(FlaskForm):

    title = StringField("Title: ", [validators.InputRequired()] , render_kw={"placeholder": "Like Car For Sale"})

    description = TextAreaField("Description: ", [validators.InputRequired()] , render_kw={"placeholder": "Like Toyota Camry model 2020 , Color-Black "})

    price = FloatField("Price: ", [validators.InputRequired()] , render_kw={"placeholder": "00.00 JDS"})

    category = SelectField(u'Category')

    image = FileField()

    submit = SubmitField("Add Item")


class EditItemForm(FlaskForm):

    new_title = StringField("Title: ", [validators.InputRequired()])

    new_description = TextAreaField("Description: ", [validators.InputRequired()])

    new_price = FloatField("Price: ", [validators.InputRequired()])

    category = SelectField(u'Category')

    new_image = FileField()

    submit = SubmitField("Edit Item")    


class AddCategoryForm(FlaskForm):
    value = StringField("Category Number: ")
    label = StringField("Category Name: ")
    submit = SubmitField("Add Category")

capstone/blueprints/home.py
from flask import Blueprint, render_template, request, redirect, session, flash , url_for
from flask_wtf import FlaskForm
from capstone.models import User , Item , Category
from capstone.forms.items import AddItemForm , EditItemForm
from capstone.models.request import BuyRequest
from bson import ObjectId
from .user import disable_user , login_required , maintenance

# define our blueprint
home_bp = Blueprint('home', __name__)






@home_bp.route('/home', methods=['POST', 'GET'])
@login_required
@disable_user
@maintenance
def home():
    """ This function is display unsold item """
    user = User.objects()
    items = Item.objects(sold = False)

    return render_template('item/home.html' ,user = user ,items = items)



@home_bp.route('/user/add_item', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def add_item():
    """This function is available for the Seller User, it provides them with a form to add an item for sale."""
    add_item_form = AddItemForm()

    categories = Category.objects()

    add_item_form.category.choices = [(category.value, category.label) for category in categories]

    if add_item_form.validate_on_submit():

        title = add_item_form.title.data
        description = add_item_form.description.data
        price = add_item_form.price.data
        category = add_item_form.category.data

        new_item = Item(user = session['user']['id'] , title = title, description = description, price = price, category = category)
        
        new_item.save()

        flash("Your item has been successfully added.")

        return redirect(url_for('home.home'))

    return render_template("item/add_item.html", form = add_item_form , title = 'Add-Item' , icon="fa fa-upload")


@home_bp.route('/user/<user_id>/edit_item/<item_id>', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def edit_item(user_id,item_id):
    """This function is available for the Seller User, it provides them with a form to edit an item of theirs.
    Another Seller user can try to edit an item that is not theirs but will be flashed by a message preventing them to do so."""
    
    edit_item_form = EditItemForm()

    categories = Category.objects()

    edit_item_form.category.choices = [(category.value, category.label) for category in categories]

    item = Item.objects(id = item_id).first()

    if request.method == "GET":

        edit_item_form.new_title.data = item.title
        edit_item_form.new_description.data = item.description
        edit_item_form.new_price.data = item.price
        edit_item_form.category.data = item.category

    if edit_item_form.validate_on_submit():

        item = Item.objects(id = item_id).first() 
        item_user = item.user
        user = User.objects(id = user_id).first()

        if user == item_user :
            item.title = edit_item_form.new_title.data
            item.description = edit_item_form.new_description.data
            item.price = edit_item_form.new_price.data
            item.category = edit_item_form.category.data
            
            item.save()

            flash("Your item has been successfully edit.")

            return redirect(url_for('home.home'))

        else: 
            flash('Not allowed')

        return redirect(url_for("home.home"))  


    return render_template("item/edit_item.html", form = edit_item_form , title = 'Edit-Item' , icon = 'far fa-edit')    

    
@home_bp.route('/user/<user_id>/delete_item/<item_id>', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def delete_item(user_id ,item_id):
    """This function is available for the Seller User, it allows them to delete an item of theirs.
    Another Seller user can try to delete an item that is not theirs but will be flashed by a message preventing them to do so."""


    item = Item.objects(id = item_id).first() 
    item_user = item.user
    user = User.objects(id = user_id).first()

    if user == item_user :
        Item.objects(id = item_id , user = user_id).first().delete()
        flash('Item has been deleted')
    else: 
        flash('Not allowed')

    return redirect(url_for("home.home"))  


@home_bp.route('/sort-item/date', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def sort_date_items():
    """This function brings items from the database ordered descendingly by the date of their addition for the user to view."""
    items = Item.objects.order_by('-date')

    return render_template("item/home.html" , items = items)        


@home_bp.route('/sort-item/price', methods=['GET', 'POST'])
@login_required
@disable_user
@maintenance
def sort_price_items():
    """This function brings items from the database ordered descendingly by their price for the user to view."""
   
    items = Item.objects.order_by('-price')

    return render_template("item/home.html" , items = items)    


@home_bp.route("/item/search", methods=['POST'])
@login_required
@disable_user
@maintenance
def search_items():
    """This function is used when a user searches for a word; it can either be in the title or description.
    If the word was in the title of an item and the description of another, the priority is for the title."""

    if request.method == 'POST':
        
        search_keyword = str(request.form['search_keyword'])  
        results = Item.objects.search_text(search_keyword).order_by('$text_score')
        
        return render_template("item/search-result.html" , items = results , search_keyword = search_keyword)  


@home_bp.route('/item/<item_id>/favorite')
@login_required
@disable_user
@maintenance
def add_favorite(item_id):
    """This function lets a Buyer user add items to the Favorites List."""

    User.objects(id = session['user']['id']).update_one(add_to_set__favorite = item_id)
    flash("Added as favorite !:)")
    return redirect(url_for('home.home'))          



@home_bp.route('/item/<item_id>/remove_favorite')
@login_required
@disable_user
@maintenance
def remove_from_favorite(item_id):
    """This function lets a Buyer user remove items from the Favorites List."""

    User.objects(id = session['user']['id']).update_one(pull__favorite = item_id)
    flash("Removed from favorite !:)")
    return redirect(url_for('profile.profile'))          


@home_bp.route('/item/<item_id>/buy')
@login_required
@disable_user
@maintenance
def buy_item(item_id):
    """This function allows a Buyer user to send a Buy Request to the seller of an item to be reviewed."""

    request = BuyRequest.objects(user = session['user']['id'], item = item_id).first()

    if not request:

        buy_request = BuyRequest(user = session['user']['id'], item = item_id, status = 'Pending')

        buy_request.save()
        
        Item.objects(id = item_id).update_one(add_to_set__buy_request_list = buy_request.id)

        flash("A Buy Requests has been Sent. !:)")


    else:
        flash("Item already in you Buy-Requests.")

    return redirect(url_for('home.home' , request = request))

capstone/templates/item/add_item.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
{% block title %}Add-Item{% endblock %}
{% endblock %}

<!-- content block -->
{% block main %}



<center>
  {% if session['user']['role'] == 1 %}

  <div>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <h2>
        <i class="{{icon}}"></i> {{title}}
      </h2>
    </div>
  </div>

  <div id="b1">
    <div class="col-lg-4 col-md-6 col-sm-12">
      <form method="POST" action="">
        {{form.hidden_tag()}}
        <div class="row my-3">
          {{form.title.label(class_="form-label")}}
          {{form.title(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.description.label(class_="form-label")}}
          {{form.description(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.price.label(class_="form-label")}}
          {{form.price(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.category.label(class_="form-label")}}
          {{form.category(class_="form-control")}}
        </div>

        <hr class="mb-4" />
        {{form.submit(class_="form-control btn btn-primary text-white")}}

      </form>

    </div>
  </div>


  {% else %}
  <br>
  <div class="alert alert-warning" role="alert">
    You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
  {% endif %}

</center>

{% endblock %}

capstone/templates/item/edit_item.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
{% block title %}Edit-Item{% endblock %}
{% endblock %}

<!-- content block -->
{% block main %}



<center>

  {% if session['user']['role'] == 1 %}

  <div>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <h2>
        <i class="{{icon}}"></i> {{title}}
      </h2>
    </div>
  </div>

  <div id="b1">
    <div class="col-lg-4 col-md-6 col-sm-12">
      <form method="POST" action="">
        {{form.hidden_tag()}}
        <div class="row my-3">
          {{form.new_title.label(class_="form-label")}}
          {{form.new_title(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.new_description.label(class_="form-label")}}
          {{form.new_description(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.new_price.label(class_="form-label")}}
          {{form.new_price(class_="form-control")}}
        </div>
        <div class="row my-3">
          {{form.category.label(class_="form-label")}}
          {{form.category(class_="form-control")}}
        </div>

        <hr class="mb-4" />
        {{form.submit(class_="form-control btn btn-primary text-white")}}

      </form>

    </div>
  </div>


  
  {% else %}
  <br>
  <div class="alert alert-warning" role="alert">
    You're not allowed to see this! back to your profile?<a href="{{url_for('profile.profile')}}"> Your-Profile </a>
  </div>
  {% endif %}
</center>

{% endblock %}

capstone/templates/item/home.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h1>{% block title %}Home{% endblock %}</h1>
{% endblock %}

<!-- content block -->
{% block main %}




<center>


  <form action="{{ url_for('home.search_items') }}" method="POST">
    <input class="form-control form-control-lg" type="search" name="search_keyword" style="width: 25%;"
      placeholder=" Enter Keywords To Search" aria-label="Search">
    <button class="btn btn-primary mt-3">Search </button>
  </form>

  <hr>
  {% if session['user']['role'] == 1  %}
  <a href="{{url_for('home.add_item')}}"> <button type="button" class="btn btn-primary">Add-Item</button></a>
  {% endif %}
  <a href="{{url_for('home.sort_price_items')}}"><button type="button" class="btn btn-primary">Sort By
      Price</button></a>
  <a href="{{url_for('home.sort_date_items')}}"><button type="button" class="btn btn-primary">Sort By Date</button></a>
  <br> <br>

  <div class="container">
    <div class="row align-items-start">
      {% for item in items %}
      <div class="col">



        <div class="card" style="width: 18rem;">

          <ol class="mr-5">
            {% if session ['user']['role'] == 0 %}
            <a href="{{url_for('home.add_favorite' , item_id = item.id)}}"><i class="fas fa-star"
                title="Favorite"></i></a>
            {% elif session ['user']['role'] == 1 or session ['user']['role'] == 2 %}
            <a href="{{url_for('home.edit_item' , item_id = item.id , user_id = session['user']['id'])}}"><i
                class="far fa-edit" title="Edit"></i></a>
            <a href="{{url_for('home.delete_item' , item_id = item.id , user_id = session['user']['id'])}}"><i
                class="fas fa-trash-alt" title="Delete"></i></a>
            {% endif %}
          </ol>

          <img class="card-img-top" src="../../static/images/logi.png" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">
              <h5
                style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
                <b> HRD-Souq</b>
              </h5>
            </h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <p class="card-text">
            <h5>Title : </b>{{item.title}}</h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <h5>Description : </b>{{item.description}}</h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <h5>Price : </b> {{item.price}} JDs </h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <h5>Cateogory : </b> {{item.category}} </h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <h5>Date : </b> {{item.date}} </h5>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">
            <h5>Seller : </b> {{item.user.first_name | title}} {{item.user.last_name | title}} </h5>
            </p>
            <hr style="height:1px;border-width:0;color:gray;background-color:gray">

            {% if session['user']['role'] == 0 %}
            <a href="{{url_for('home.buy_item' , item_id = item.id)}}" class="btn btn-primary text-white">Buy</a>
            {% else %}
            <a class="btn btn-primary text-white disabled">Buy</a>
            {% endif %}


          </div>
        </div>
        <hr style="height:1px;border-width:0;color:gray;background-color:gray">
        <br>

      </div>

      {% endfor %}


    </div>
  </div>


  {% if not items %}
  <P>No Items, Do You Want To ADD An Item?<a href="{{url_for('home.add_item')}}"> Add-Item</a> </P>
  {% endif %}
</center>

{% endblock %}

capstone/templates/item/search-result.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Searched Items{% endblock %}</h1>
<P>Found {{items | count}} result from {{search_keyword}}</P>

{% endblock %}

<!-- content block -->
{% block main %}
<center>
{% if items %}
    {% for item in items %}
    
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="../../static/images/logi.png" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">
            <h5><b>HRD-Souq.com</b></h5>
          </h5>
          <hr style="height:2px;border-width:0;color:gray;background-color:gray">
          <p class="card-text">
          <h5><b>Title : </b>{{item.title}}</h5>
          <hr style="height:2px;border-width:0;color:gray;background-color:gray">
          <h5><b>Description : </b>{{item.description}}</h5>
          <hr style="height:2px;border-width:0;color:gray;background-color:gray">
          <h5><b>Price : </b> {{item.price}} JDs </h5>
          <hr style="height:2px;border-width:0;color:gray;background-color:gray">
          </p>
          <a href="#" class="btn btn-primary text-white">Buy</a>
        </div>
      </div>
    {% endfor %}
{% else %}
<P>Nothing found with the word "{{search_keyword}}"</P>
{% endif %}
</center>
{% endblock %}